#define EXPOSE_FUNCTION_OVERLOAD_ARGS_1(EXPR, C_TYPE, AIR_TYPE) \
__attribute__((__overloadable__)) C_TYPE EXPR(C_TYPE data) \
  __asm("air." #EXPR "." #AIR_TYPE); \

#define EXPOSE_FUNCTION_SCALAR_ARGS_11(EXPR) \
EXPOSE_FUNCTION_OVERLOAD_ARGS_1(EXPR, char, s.i8) \
EXPOSE_FUNCTION_OVERLOAD_ARGS_1(EXPR, short, s.i16) \
EXPOSE_FUNCTION_OVERLOAD_ARGS_1(EXPR, int, s.i32) \
EXPOSE_FUNCTION_OVERLOAD_ARGS_1(EXPR, long, s.i64) \
EXPOSE_FUNCTION_OVERLOAD_ARGS_1(EXPR, uchar, u.u8) \
EXPOSE_FUNCTION_OVERLOAD_ARGS_1(EXPR, ushort, u.u16) \
EXPOSE_FUNCTION_OVERLOAD_ARGS_1(EXPR, uint, u.u32) \
EXPOSE_FUNCTION_OVERLOAD_ARGS_1(EXPR, ulong, u.u64) \
EXPOSE_FUNCTION_OVERLOAD_ARGS_1(EXPR, float, f32) \

#define EXPOSE_FUNCTION_SCALAR_ARGS_12(EXPR) \
EXPOSE_FUNCTION_OVERLOAD_ARGS_1(EXPR, char, s.i8) \
EXPOSE_FUNCTION_OVERLOAD_ARGS_1(EXPR, short, s.i16) \
EXPOSE_FUNCTION_OVERLOAD_ARGS_1(EXPR, int, s.i32) \
EXPOSE_FUNCTION_OVERLOAD_ARGS_1(EXPR, long, s.i64) \
EXPOSE_FUNCTION_OVERLOAD_ARGS_1(EXPR, float, f32) \

#define EXPOSE_FUNCTION_VECTOR_ARGS_11(EXPR, VEC_SIZE) \
EXPOSE_FUNCTION_OVERLOAD_ARGS_1(EXPR, char##VEC_SIZE, s.v##VEC_SIZE##i8) \
EXPOSE_FUNCTION_OVERLOAD_ARGS_1(EXPR, short##VEC_SIZE, s.v##VEC_SIZE##i16) \
EXPOSE_FUNCTION_OVERLOAD_ARGS_1(EXPR, int##VEC_SIZE, s.v##VEC_SIZE##i32) \
EXPOSE_FUNCTION_OVERLOAD_ARGS_1(EXPR, long##VEC_SIZE, s.v##VEC_SIZE##i64) \
EXPOSE_FUNCTION_OVERLOAD_ARGS_1(EXPR, uchar##VEC_SIZE, u.v##VEC_SIZE##u8) \
EXPOSE_FUNCTION_OVERLOAD_ARGS_1(EXPR, ushort##VEC_SIZE, u.v##VEC_SIZE##u16) \
EXPOSE_FUNCTION_OVERLOAD_ARGS_1(EXPR, uint##VEC_SIZE, u.v##VEC_SIZE##u32) \
EXPOSE_FUNCTION_OVERLOAD_ARGS_1(EXPR, ulong##VEC_SIZE, u.v##VEC_SIZE##u64) \
EXPOSE_FUNCTION_OVERLOAD_ARGS_1(EXPR, float##VEC_SIZE, v##VEC_SIZE##f32) \

#define EXPOSE_FUNCTION_VECTOR_ARGS_12(EXPR, VEC_SIZE) \
EXPOSE_FUNCTION_OVERLOAD_ARGS_1(EXPR, char##VEC_SIZE, s.v##VEC_SIZE##i8) \
EXPOSE_FUNCTION_OVERLOAD_ARGS_1(EXPR, short##VEC_SIZE, s.v##VEC_SIZE##i16) \
EXPOSE_FUNCTION_OVERLOAD_ARGS_1(EXPR, int##VEC_SIZE, s.v##VEC_SIZE##i32) \
EXPOSE_FUNCTION_OVERLOAD_ARGS_1(EXPR, long##VEC_SIZE, s.v##VEC_SIZE##i64) \
EXPOSE_FUNCTION_OVERLOAD_ARGS_1(EXPR, float##VEC_SIZE, v##VEC_SIZE##f32) \

#define EXPOSE_FUNCTION_ARGS_11(EXPR) \
EXPOSE_FUNCTION_SCALAR_ARGS_11(EXPR) \
EXPOSE_FUNCTION_VECTOR_ARGS_11(EXPR,2) \
EXPOSE_FUNCTION_VECTOR_ARGS_11(EXPR,3) \
EXPOSE_FUNCTION_VECTOR_ARGS_11(EXPR,4) \

#define EXPOSE_FUNCTION_ARGS_12(EXPR) \
EXPOSE_FUNCTION_SCALAR_ARGS_12(EXPR) \
EXPOSE_FUNCTION_VECTOR_ARGS_12(EXPR,2) \
EXPOSE_FUNCTION_VECTOR_ARGS_12(EXPR,3) \
EXPOSE_FUNCTION_VECTOR_ARGS_12(EXPR,4) \

#define BRIDGE_ZEXT_OVERLOAD_ARGS_1(EXPR, SIGNED_TYPE, UNSIGNED_TYPE) \
__attribute__((__overloadable__)) \
UNSIGNED_TYPE EXPR(UNSIGNED_TYPE x) { \
  return UNSIGNED_TYPE(EXPR(SIGNED_TYPE(x))); \
}

#define BRIDGE_ZEXT_SCALAR_ARGS_1(EXPR) \
BRIDGE_ZEXT_OVERLOAD_ARGS_1(EXPR, char, uchar) \
BRIDGE_ZEXT_OVERLOAD_ARGS_1(EXPR, short, ushort) \
BRIDGE_ZEXT_OVERLOAD_ARGS_1(EXPR, int, uint) \
BRIDGE_ZEXT_OVERLOAD_ARGS_1(EXPR, long, ulong) \

#define BRIDGE_ZEXT_VECTOR_ARGS_1(EXPR, VEC_SIZE) \
BRIDGE_ZEXT_OVERLOAD_ARGS_1(EXPR, char##VEC_SIZE, uchar##VEC_SIZE) \
BRIDGE_ZEXT_OVERLOAD_ARGS_1(EXPR, short##VEC_SIZE, ushort##VEC_SIZE) \
BRIDGE_ZEXT_OVERLOAD_ARGS_1(EXPR, int##VEC_SIZE, uint##VEC_SIZE) \
BRIDGE_ZEXT_OVERLOAD_ARGS_1(EXPR, long##VEC_SIZE, ulong##VEC_SIZE) \

#define BRIDGE_ZEXT_ARGS_1(EXPR) \
BRIDGE_ZEXT_SCALAR_ARGS_1(EXPR) \
BRIDGE_ZEXT_VECTOR_ARGS_1(EXPR, 2) \
BRIDGE_ZEXT_VECTOR_ARGS_1(EXPR, 3) \
BRIDGE_ZEXT_VECTOR_ARGS_1(EXPR, 4) \

#define BRIDGE_FUNCTION_OVERLOAD_ARGS_1(METAL_EXPR, OPENCL_EXPR, C_TYPE) \
__attribute__((__overloadable__)) \
C_TYPE OPENCL_EXPR(C_TYPE x) { \
  return METAL_EXPR(x); \
}

#define BRIDGE_FUNCTION_ARGS_1(METAL_EXPR, OPENCL_EXPR) \
BRIDGE_FUNCTION_OVERLOAD_ARGS_1(METAL_EXPR, OPENCL_EXPR, int) \
BRIDGE_FUNCTION_OVERLOAD_ARGS_1(METAL_EXPR, OPENCL_EXPR, long) \
BRIDGE_FUNCTION_OVERLOAD_ARGS_1(METAL_EXPR, OPENCL_EXPR, uint) \
BRIDGE_FUNCTION_OVERLOAD_ARGS_1(METAL_EXPR, OPENCL_EXPR, ulong) \
BRIDGE_FUNCTION_OVERLOAD_ARGS_1(METAL_EXPR, OPENCL_EXPR, float) \

EXPOSE_FUNCTION_ARGS_11(simd_sum)
EXPOSE_FUNCTION_ARGS_12(simd_prefix_inclusive_sum)
BRIDGE_ZEXT_ARGS_1(simd_prefix_inclusive_sum)
BRIDGE_FUNCTION_ARGS_1(simd_prefix_inclusive_sum, sub_group_scan_inclusive_add)

#undef BRIDGE_FUNCTION_OVERLOAD_ARGS_1
#undef EXPOSE_FUNCTION_ARGS_1
#undef EXPOSE_FUNCTION_SCALAR_ARGS_1
#undef EXPOSE_FUNCTION_VECTOR_ARGS_1
#undef EXPOSE_FUNCTION_OVERLOAD_ARGS_1
